apiVersion: apps/v1
kind: Deployment
metadata:
  name: department-service
  labels:
    app: department-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: department-service
  template:
    metadata:
      labels:
        app: department-service
    spec:
      containers:
        - name: department-service
          image: meibohu/department-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

---

kind: Service
apiVersion: v1
metadata:
  name: department-service
spec:
  selector:
    app: department-service
  ports:
    - port:  80
      targetPort:  8080